# Generated by Django 3.1.2 on 2020-12-08 01:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('organic', models.BooleanField(null=True)),
                ('treated', models.BooleanField(null=True)),
                ('hybrid', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'genus',
            },
        ),
        migrations.CreateModel(
            name='Grow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(choices=[('F', 'Full sun'), ('P', 'Part sun'), ('S', 'Shade')], default=None, max_length=1, null=True)),
                ('soil', models.CharField(max_length=30, null=True)),
                ('crop', models.ForeignKey(db_column='gr_cr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.crop')),
            ],
            options={
                'db_table': 'grow',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Unnamed Plot', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('area', models.FloatField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.plot')),
            ],
            options={
                'db_table': 'plot',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('common_name', models.CharField(max_length=30, null=True)),
                ('genus', models.ForeignKey(db_column='genus', on_delete=django.db.models.deletion.CASCADE, to='aria.genus')),
            ],
            options={
                'db_table': 'species',
                'unique_together': {('id', 'genus')},
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('set', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('plot', models.ForeignKey(db_column='pt_plt_num', on_delete=django.db.models.deletion.CASCADE, to='aria.plot')),
            ],
            options={
                'db_table': 'point',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('R', 'Row'), ('M', 'Mound'), ('P', 'Pot'), ('T', 'Trellis'), ('S', 'Scatter')], default=None, max_length=1)),
                ('spacing', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('frost', models.CharField(choices=[('F', 'First frost'), ('L', 'Last frost')], default=None, max_length=1)),
                ('date', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(choices=[('I', 'Start inside'), ('O', 'Direct sow')], default=None, max_length=1)),
                ('temperature', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ('germination', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('depth', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('crop', models.ForeignKey(db_column='pl_cr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.crop')),
                ('transplant', models.ForeignKey(db_column='pl_transplant', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.plant')),
            ],
            options={
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('variety', models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed'), ('L', 'Legume')], default=None, max_length=1, null=True)),
                ('crop', models.ForeignKey(db_column='har_cr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.crop')),
                ('grow', models.ForeignKey(db_column='har_gr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.grow')),
                ('plant', models.ForeignKey(db_column='har_pl_num', on_delete=django.db.models.deletion.CASCADE, to='aria.plant')),
            ],
            options={
                'db_table': 'harvest',
            },
        ),
        migrations.AddField(
            model_name='grow',
            name='plant',
            field=models.ForeignKey(db_column='gr_pl_num', on_delete=django.db.models.deletion.CASCADE, to='aria.plant'),
        ),
        migrations.AddField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(db_column='species', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.species'),
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.ForeignKey(db_column='sub_sp_num', on_delete=django.db.models.deletion.CASCADE, to='aria.species')),
            ],
            options={
                'db_table': 'subspecies',
                'unique_together': {('id', 'species')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('id', 'species')},
        ),
    ]
