# Generated by Django 3.0.6 on 2020-10-28 04:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('cr_num', models.IntegerField(primary_key=True, serialize=False)),
                ('cr_variety', models.CharField(max_length=50)),
                ('cr_description', models.TextField(null=True)),
                ('cr_company', models.CharField(max_length=30, null=True)),
                ('cr_organic', models.BooleanField(null=True)),
                ('cr_treated', models.BooleanField(null=True)),
                ('cr_hybrid', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('ge_num', models.IntegerField(primary_key=True, serialize=False)),
                ('ge_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'genus',
            },
        ),
        migrations.CreateModel(
            name='Grow',
            fields=[
                ('gr_num', models.IntegerField(primary_key=True, serialize=False)),
                ('gr_sun', models.CharField(choices=[('F', 'Full sun'), ('P', 'Part sun'), ('S', 'Shade')], default=None, max_length=1, null=True)),
                ('gr_soil', models.CharField(max_length=30, null=True)),
                ('gr_cr_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Crop')),
            ],
            options={
                'db_table': 'grow',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('sp_num', models.IntegerField(primary_key=True, serialize=False)),
                ('sp_name', models.CharField(max_length=30)),
                ('sp_common_name', models.CharField(max_length=30, null=True)),
                ('sp_ge_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Genus')),
            ],
            options={
                'db_table': 'species',
                'unique_together': {('sp_num', 'sp_ge_num')},
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plt_num', models.IntegerField(primary_key=True, serialize=False)),
                ('plt_cr_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aria.Crop')),
                ('plt_parent_num', models.ForeignKey(db_column='garden', on_delete=django.db.models.deletion.CASCADE, to='aria.Plot')),
            ],
            options={
                'db_table': 'plot',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('pl_num', models.IntegerField(primary_key=True, serialize=False)),
                ('pl_pattern', models.CharField(choices=[('R', 'Row'), ('M', 'Mound'), ('P', 'Pot'), ('T', 'Trellis'), ('S', 'Scatter')], default=None, max_length=1)),
                ('pl_spacing', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pl_frost', models.CharField(choices=[('F', 'First frost'), ('L', 'Last frost')], default=None, max_length=1)),
                ('pl_date', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('pl_location', models.CharField(choices=[('I', 'Start inside'), ('O', 'Direct sow')], default=None, max_length=1)),
                ('pl_temperature', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ('pl_germination', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('pl_depth', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('pl_cr_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Crop')),
                ('pl_transplant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant')),
            ],
            options={
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('har_num', models.IntegerField(primary_key=True, serialize=False)),
                ('har_begin', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('har_end', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('har_variety', models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed'), ('L', 'Legume')], default=None, max_length=1, null=True)),
                ('har_cr_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Crop')),
                ('har_gr_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Grow')),
                ('har_pl_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Plant')),
            ],
            options={
                'db_table': 'harvest',
            },
        ),
        migrations.AddField(
            model_name='grow',
            name='gr_pl_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
        migrations.AddField(
            model_name='crop',
            name='cr_sp_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Species'),
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('sub_num', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=30)),
                ('sub_sp_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Species')),
            ],
            options={
                'db_table': 'subspecies',
                'unique_together': {('sub_num', 'sub_sp_num')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('cr_num', 'cr_sp_num')},
        ),
    ]
