# Generated by Django 3.1.2 on 2020-12-08 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.species'),
        ),
        migrations.AlterField(
            model_name='grow',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.crop'),
        ),
        migrations.AlterField(
            model_name='grow',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plant'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.crop'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='grow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.grow'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.crop'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.plot'),
        ),
        migrations.AlterField(
            model_name='point',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plot'),
        ),
        migrations.AlterField(
            model_name='species',
            name='genus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.genus'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.species'),
        ),
    ]
