# Generated by Django 3.1.2 on 2020-12-15 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'field'), ('W', 'forest'), ('G', 'garden'), ('O', 'orchard'), ('P', 'pasture'), ('S', 'silvopasture')], default=None, max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
        migrations.AlterField(
            model_name='field',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
        migrations.AlterField(
            model_name='forest',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
        migrations.AlterField(
            model_name='orchard',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
        migrations.AlterField(
            model_name='pasture',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
        migrations.AlterField(
            model_name='silvopasture',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.plottype'),
        ),
    ]
