# Generated by Django 3.1.2 on 2020-12-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.CharField(blank=True, choices=[('F', 'field'), ('W', 'forest'), ('G', 'garden'), ('O', 'orchard'), ('P', 'pasture'), ('S', 'silvopasture')], default=None, max_length=1, null=True),
        ),
    ]
