# Generated by Django 3.0.3 on 2020-04-05 02:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='germination',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='temperature',
        ),
        migrations.AddField(
            model_name='crop',
            name='depth',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='crop',
            name='germination',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='crop',
            name='temperature',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
