# Generated by Django 3.0.6 on 2020-10-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0002_auto_20201027_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='cr_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grow',
            name='gr_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='har_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pl_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plt_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='sp_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='sub_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
