# Generated by Django 3.1.2 on 2020-12-09 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0002_auto_20201207_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('F', 'Marker'), ('P', 'Line'), ('S', 'Polygon')], default=None, max_length=1, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shape',
            },
        ),
        migrations.RemoveField(
            model_name='plot',
            name='area',
        ),
        migrations.RemoveField(
            model_name='point',
            name='plot',
        ),
        migrations.AddField(
            model_name='plot',
            name='shape',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.shape'),
        ),
        migrations.AddField(
            model_name='point',
            name='shape',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.shape'),
        ),
    ]
