# Generated by Django 3.1.2 on 2020-12-28 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aria', '0003_auto_20201228_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
