# Generated by Django 3.1.2 on 2020-12-19 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0003_plot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aria.species'),
            preserve_default=False,
        ),
    ]
