# Generated by Django 3.1.2 on 2020-12-19 03:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0004_auto_20201218_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grow',
            name='soil',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grow',
            name='sun',
            field=models.CharField(blank=True, choices=[('F', 'Full sun'), ('P', 'Part sun'), ('S', 'Shade')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='depth',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='planting',
            name='germination',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='planting',
            name='temperature',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='planting',
            name='transplant',
            field=models.ForeignKey(blank=True, db_column='pl_transplant', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.planting'),
        ),
    ]
