# Generated by Django 3.0.6 on 2020-10-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0004_auto_20201027_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='cr_sp_num',
            field=models.ForeignKey(db_column='cr_sp_num', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Species'),
        ),
        migrations.AlterField(
            model_name='grow',
            name='gr_cr_num',
            field=models.ForeignKey(db_column='gr_cr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Crop'),
        ),
        migrations.AlterField(
            model_name='grow',
            name='gr_pl_num',
            field=models.ForeignKey(db_column='gr_pl_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='har_cr_num',
            field=models.ForeignKey(db_column='har_cr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Crop'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='har_gr_num',
            field=models.ForeignKey(db_column='har_gr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Grow'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='har_pl_num',
            field=models.ForeignKey(db_column='har_pl_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pl_cr_num',
            field=models.ForeignKey(db_column='pl_cr_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Crop'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pl_transplant',
            field=models.ForeignKey(db_column='pl_transplant', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plt_cr_num',
            field=models.ForeignKey(db_column='plt_cr_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aria.Crop'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plt_parent_num',
            field=models.ForeignKey(db_column='plt_parent_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Plot'),
        ),
        migrations.AlterField(
            model_name='subspecies',
            name='sub_sp_num',
            field=models.ForeignKey(db_column='sub_sp_num', on_delete=django.db.models.deletion.CASCADE, to='aria.Species'),
        ),
    ]
