# Generated by Django 3.0.3 on 2020-04-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0004_auto_20200407_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pattern',
            field=models.CharField(choices=[('R', 'row'), ('M', 'mound'), ('P', 'pot'), ('T', 'trellis'), ('S', 'scatter')], default=None, max_length=1),
        ),
    ]
