# Generated by Django 3.0.3 on 2020-04-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0005_auto_20200407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='frost',
            field=models.CharField(choices=[('F', 'first frost'), ('L', 'last frost')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('I', 'start inside'), ('O', 'direct sow'), ('T', 'transplant')], default=None, max_length=1),
        ),
    ]
