# Generated by Django 3.1.2 on 2020-12-03 01:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0005_auto_20201027_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('pt_num', models.AutoField(primary_key=True, serialize=False)),
                ('pt_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pt_lat', models.FloatField()),
                ('pt_long', models.FloatField()),
                ('pt_plt_num', models.ForeignKey(db_column='pt_plt_num', on_delete=django.db.models.deletion.CASCADE, to='aria.plot')),
            ],
            options={
                'db_table': 'point',
            },
        ),
    ]
