# Generated by Django 3.1.2 on 2021-01-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0005_auto_20210107_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(blank=True, choices=[('F', 'Full sun'), ('P', 'Part sun'), ('S', 'Shade')], default=None, max_length=1, null=True)),
                ('soil', models.CharField(blank=True, max_length=30, null=True)),
                ('water', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.crop')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.planting')),
            ],
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='grow',
        ),
        migrations.DeleteModel(
            name='Grow',
        ),
        migrations.AddField(
            model_name='harvest',
            name='care',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aria.cropcare'),
            preserve_default=False,
        ),
    ]
