# Generated by Django 3.1.2 on 2020-12-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0005_auto_20201218_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zone', models.CharField(max_length=2)),
                ('firstFrost', models.DateField()),
                ('lastFrost', models.DateField()),
                ('yearlyRainfall', models.IntegerField()),
                ('januaryRain', models.IntegerField()),
                ('januaryAvgHigh', models.IntegerField()),
                ('januaryAvgLow', models.IntegerField()),
                ('februaryRain', models.IntegerField()),
                ('februaryAvgHigh', models.IntegerField()),
                ('februaryAvgLow', models.IntegerField()),
                ('marchRain', models.IntegerField()),
                ('marchAvgHigh', models.IntegerField()),
                ('marchAvgLow', models.IntegerField()),
                ('aprilRain', models.IntegerField()),
                ('aprilAvgHigh', models.IntegerField()),
                ('aprilAvgLow', models.IntegerField()),
                ('mayRain', models.IntegerField()),
                ('mayAvgHigh', models.IntegerField()),
                ('mayAvgLow', models.IntegerField()),
                ('juneRain', models.IntegerField()),
                ('juneAvgHigh', models.IntegerField()),
                ('juneAvgLow', models.IntegerField()),
                ('julyRain', models.IntegerField()),
                ('julyAvgHigh', models.IntegerField()),
                ('julyAvgLow', models.IntegerField()),
                ('augustRain', models.IntegerField()),
                ('augustAvgHigh', models.IntegerField()),
                ('augustAvgLow', models.IntegerField()),
                ('septemberRain', models.IntegerField()),
                ('septemberAvgHigh', models.IntegerField()),
                ('septemberAvgLow', models.IntegerField()),
                ('octoberRain', models.IntegerField()),
                ('octoberAvgHigh', models.IntegerField()),
                ('octoberAvgLow', models.IntegerField()),
                ('novemberRain', models.IntegerField()),
                ('novemberAvgHigh', models.IntegerField()),
                ('novemberAvgLow', models.IntegerField()),
                ('decemberRain', models.IntegerField()),
                ('decemberAvgHigh', models.IntegerField()),
                ('decemberAvgLow', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.climate'),
        ),
    ]
