# Generated by Django 3.1.2 on 2020-12-03 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0006_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plt_parent_num',
            field=models.ForeignKey(db_column='plt_parent_num', null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.plot'),
        ),
    ]
