# Generated by Django 3.1.2 on 2021-01-10 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0006_auto_20210110_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropcare',
            name='water',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
