# Generated by Django 3.0.3 on 2020-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0006_auto_20200407_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='pattern',
            field=models.CharField(choices=[('R', 'plant in rows'), ('M', 'plant in mounds'), ('P', 'plant in pots'), ('T', 'plant along trellises'), ('S', 'scatter plant')], default=None, max_length=1),
        ),
    ]
