# Generated by Django 3.1.2 on 2021-01-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0007_auto_20210110_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropcare',
            name='sun',
            field=models.CharField(choices=[('F', 'Full sun'), ('P', 'Part sun'), ('S', 'Shade')], default=None, max_length=1),
        ),
    ]
