# Generated by Django 3.1.2 on 2020-12-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0007_auto_20201202_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='plt_name',
            field=models.CharField(default='UNNAMED', max_length=128),
            preserve_default=False,
        ),
    ]
