# Generated by Django 3.1.2 on 2020-12-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0007_auto_20201218_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='variety',
            new_name='name',
        ),
    ]
