# Generated by Django 3.1.2 on 2021-02-07 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0008_auto_20210110_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='variety',
            field=models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='pattern',
            field=models.CharField(choices=[('R', 'in rows'), ('M', 'in mounds'), ('P', 'in pots'), ('T', 'on trellises'), ('S', 'by scattering')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='planting',
            name='transplant',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(52)]),
        ),
    ]
