# Generated by Django 3.1.2 on 2020-12-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0009_auto_20201202_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='plt_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
