# Generated by Django 3.1.2 on 2021-02-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0009_auto_20210206_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='care',
        ),
    ]
