# Generated by Django 3.1.2 on 2020-12-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0009_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='zone',
            new_name='climate',
        ),
    ]
