# Generated by Django 3.0.6 on 2020-10-17 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0010_merge_20201013_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='germination',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='temperature',
        ),
        migrations.AddField(
            model_name='plant',
            name='depth',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='germination',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='plant',
            name='temperature',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
