# Generated by Django 3.1.2 on 2021-02-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0010_remove_harvest_care'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvest',
            name='plant',
        ),
    ]
