# Generated by Django 3.1.2 on 2020-12-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0010_plot_plt_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='plt_description',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
