# Generated by Django 3.1.2 on 2020-12-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0011_plot_plt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plt_description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plt_name',
            field=models.CharField(default='Unnamed Plot', max_length=128),
        ),
    ]
