# Generated by Django 3.0.6 on 2020-10-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0011_auto_20201016_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='transplant',
            field=models.BooleanField(null=True),
        ),
    ]
