# Generated by Django 3.1.2 on 2020-12-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0011_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='shape',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.shape'),
        ),
    ]
