# Generated by Django 3.1.2 on 2021-02-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0012_auto_20210209_2052'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='harvest',
            table=None,
        ),
    ]
