# Generated by Django 3.1.2 on 2020-12-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0012_auto_20201205_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='plt_description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plt_name',
            field=models.CharField(blank=True, default='Unnamed Plot', max_length=128),
        ),
    ]
