# Generated by Django 3.1.2 on 2020-12-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0012_auto_20201220_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
