# Generated by Django 3.1.2 on 2021-02-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0013_auto_20210209_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropcare',
            name='plant',
        ),
    ]
