# Generated by Django 3.1.2 on 2020-12-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0013_auto_20201220_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aria.farm'),
            preserve_default=False,
        ),
    ]
