# Generated by Django 3.1.2 on 2020-12-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0014_plot_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='climate',
        ),
        migrations.AddField(
            model_name='farm',
            name='climate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.climate'),
        ),
    ]
