# Generated by Django 3.1.2 on 2021-02-11 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0014_remove_cropcare_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planting',
            old_name='germination',
            new_name='germinationEnd',
        ),
        migrations.RenameField(
            model_name='planting',
            old_name='interRowSpacing',
            new_name='interRowSpacingMax',
        ),
        migrations.RenameField(
            model_name='planting',
            old_name='rowSpacing',
            new_name='interRowSpacingMin',
        ),
        migrations.RemoveField(
            model_name='cropcare',
            name='sun',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='temperature',
        ),
        migrations.AddField(
            model_name='cropcare',
            name='frostHardy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropcare',
            name='sunMax',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='cropcare',
            name='sunMin',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='planting',
            name='germinationStart',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='planting',
            name='rowSpacingMax',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='planting',
            name='rowSpacingMin',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='planting',
            name='soilTemperatureMax',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='planting',
            name='soilTemperatureMin',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cropcare',
            name='water',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='planting',
            name='depth',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
