# Generated by Django 3.2.2 on 2021-05-22 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seedbank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedbank",
            name="quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="seedbank",
            name="year",
            field=models.IntegerField(default=2021),
        ),
    ]
