# Generated by Django 3.2.2 on 2021-05-23 00:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0003_auto_20210517_1045"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("seedbank", "0002_auto_20210522_1425"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seedbank",
            unique_together={("user", "crop", "year")},
        ),
    ]
