# Generated by Django 3.2.2 on 2021-05-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seedbank", "0003_alter_seedbank_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedbank",
            name="company",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
