# Generated by Django 3.1.2 on 2021-02-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('organic', models.BooleanField(null=True)),
                ('treated', models.BooleanField(null=True)),
                ('hybrid', models.BooleanField(null=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxonomy.species')),
            ],
            options={
                'db_table': 'crop',
                'unique_together': {('id', 'species')},
            },
        ),
    ]
