# Generated by Django 3.1.2 on 2021-02-26 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frost', models.CharField(choices=[('F', 'First frost'), ('L', 'Last frost')], default='L', max_length=1, null=True)),
                ('date', models.SmallIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(choices=[('I', 'Start inside'), ('O', 'Direct sow')], default='I', max_length=1, null=True)),
                ('transplant', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(52)])),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
            options={
                'db_table': 'plantingdate',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(blank=True, choices=[('R', 'in rows'), ('M', 'in mounds'), ('P', 'in pots'), ('T', 'on trellises'), ('S', 'by scattering')], default='R', max_length=1, null=True)),
                ('rowSpacingMin', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rowSpacingMax', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('interRowSpacingMin', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('interRowSpacingMax', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('soilTemperatureMin', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
                ('soilTemperatureMax', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
                ('germinationStart', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('germinationEnd', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('depth', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
            options={
                'db_table': 'planting',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('variety', models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed')], default='F', max_length=1, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
            options={
                'db_table': 'harvest',
            },
        ),
        migrations.CreateModel(
            name='CropCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunMin', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('sunMax', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('soil', models.CharField(blank=True, max_length=30, null=True)),
                ('water', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('frostHardy', models.BooleanField(blank=True, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.crop')),
            ],
            options={
                'db_table': 'cropcare',
            },
        ),
    ]
