# Generated by Django 3.2.2 on 2021-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0002_cropcare_harvest_planting_plantingdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="company",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="hybrid",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="organic",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="crop",
            name="treated",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="harvest",
            name="variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("R", "Root"),
                    ("G", "Leafy green"),
                    ("F", "Fruit"),
                    ("N", "Nut"),
                    ("S", "Seed"),
                ],
                default="F",
                max_length=1,
                null=True,
            ),
        ),
    ]
