# Generated by Django 3.2.2 on 2021-06-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crop", "0004_remove_crop_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planting",
            name="interRowSpacingMax",
        ),
        migrations.RemoveField(
            model_name="planting",
            name="interRowSpacingMin",
        ),
        migrations.RemoveField(
            model_name="planting",
            name="pattern",
        ),
        migrations.RemoveField(
            model_name="planting",
            name="rowSpacingMax",
        ),
        migrations.RemoveField(
            model_name="planting",
            name="rowSpacingMin",
        ),
        migrations.RemoveField(
            model_name="plantingdate",
            name="crop",
        ),
        migrations.AddField(
            model_name="plantingdate",
            name="planting",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crop.planting",
            ),
        ),
    ]
