# Generated by Django 3.2.4 on 2021-06-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                (
                    "kingdom",
                    models.CharField(
                        choices=[("P", "plantae"), ("A", "Animalae"), ("F", "Fungus")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "db_table": "genus",
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("common_name", models.CharField(max_length=30, null=True)),
                ("description", models.CharField(max_length=256)),
                (
                    "genus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.genus"
                    ),
                ),
            ],
            options={
                "db_table": "species",
                "unique_together": {("id", "genus")},
            },
        ),
        migrations.CreateModel(
            name="Subspecies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.species",
                    ),
                ),
            ],
            options={
                "db_table": "subspecies",
                "unique_together": {("id", "species")},
            },
        ),
    ]
