# Generated by Django 3.2.2 on 2021-05-18 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0002_species_kingdom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="kingdom",
        ),
        migrations.AddField(
            model_name="genus",
            name="kingdom",
            field=models.CharField(
                choices=[("P", "plantae"), ("A", "Animalae"), ("F", "Fungus")],
                default="P",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
