# Generated by Django 3.2.2 on 2021-05-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0003_auto_20210517_2138"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="description",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
