# Generated by Django 3.1.2 on 2021-02-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.plot')),
            ],
        ),
    ]
