# Generated by Django 3.1.2 on 2021-02-19 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plot', '0001_initial'),
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockRate', models.FloatField()),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plot.plot')),
            ],
        ),
    ]
