# Generated by Django 3.2.2 on 2021-06-04 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plot", "0003_plot_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plot",
            old_name="owner",
            new_name="farmer",
        ),
    ]
