# Generated by Django 3.1.2 on 2021-03-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20210228_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
