# Generated by Django 3.1.2 on 2021-03-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_farm_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
