# Generated by Django 3.1.2 on 2021-03-02 04:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0006_farm_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='farm',
            unique_together={('owner', 'name')},
        ),
    ]
