# Generated by Django 3.1.2 on 2021-03-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20210301_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
