# Generated by Django 3.1.2 on 2021-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_auto_20210302_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
