# Generated by Django 3.1.2 on 2021-03-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_auto_20210302_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='address2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
