# Generated by Django 3.1.2 on 2021-03-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_auto_20210303_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
