# Generated by Django 3.2.2 on 2021-05-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geometry", "0002_auto_20210227_1953"),
        ("climate", "0003_auto_20210227_1900"),
        ("farm", "0011_farm_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="climate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="climate.climate",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geometry.point",
            ),
        ),
    ]
