# Generated by Django 3.2.2 on 2021-05-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0012_auto_20210515_0642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(
                default="<django.db.models.fields.related.ForeignKey>'s Farm",
                max_length=128,
            ),
        ),
    ]
