# Generated by Django 3.2.2 on 2021-05-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0013_alter_farm_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="name",
            field=models.CharField(default="My Farm", max_length=128),
        ),
    ]
