# Generated by Django 3.2.2 on 2021-05-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0014_alter_farm_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
