# Generated by Django 3.2.2 on 2021-06-04 05:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farm", "0015_alter_farm_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farm",
            old_name="owner",
            new_name="farmer",
        ),
        migrations.AlterUniqueTogether(
            name="farm",
            unique_together={("farmer", "name")},
        ),
    ]
