# Generated by Django 3.2.4 on 2021-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
