# Generated by Django 3.2.2 on 2021-06-04 05:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0002_auto_20210603_2201"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calendar",
            old_name="owner",
            new_name="farmer",
        ),
        migrations.AlterUniqueTogether(
            name="calendar",
            unique_together={("id", "farmer")},
        ),
    ]
