# Generated by Django 3.2.2 on 2021-06-04 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedule", "0003_auto_20210603_2205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="farmer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="calendar",
            unique_together=set(),
        ),
    ]
