# Generated by Django 3.2.4 on 2021-06-06 05:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HardinessZone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zone",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(13),
                        ]
                    ),
                ),
                (
                    "subZone",
                    models.CharField(choices=[("a", "a"), ("b", "b")], max_length=1),
                ),
                (
                    "lowRange",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-65),
                            django.core.validators.MaxValueValidator(65),
                        ],
                    ),
                ),
                (
                    "highRange",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-65),
                            django.core.validators.MaxValueValidator(65),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "hardinesszone",
            },
        ),
        migrations.CreateModel(
            name="Climate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstFrost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firstFrost",
                        to="schedule.event",
                    ),
                ),
                (
                    "lastFrost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lastFrost",
                        to="schedule.event",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        default=13,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="climate.hardinesszone",
                    ),
                ),
            ],
            options={
                "db_table": "climate",
            },
        ),
    ]
