# Generated by Django 3.1.2 on 2021-02-25 23:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HardinessZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)])),
                ('subZone', models.CharField(choices=[('a', 'a'), ('b', 'b')], max_length=1)),
                ('lowRange', models.IntegerField(validators=[django.core.validators.MinValueValidator(-65), django.core.validators.MaxValueValidator(65)])),
                ('highRange', models.IntegerField(validators=[django.core.validators.MinValueValidator(-65), django.core.validators.MaxValueValidator(65)])),
            ],
            options={
                'db_table': 'hardinesszone',
            },
        ),
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='climate.hardinesszone')),
            ],
            options={
                'db_table': 'climate',
            },
        ),
    ]
