# Generated by Django 3.2.4 on 2021-06-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_alter_event_description"),
        ("climate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="climate",
            name="firstFrost",
        ),
        migrations.RemoveField(
            model_name="climate",
            name="lastFrost",
        ),
        migrations.AddField(
            model_name="climate",
            name="growing_season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedule.event",
            ),
        ),
    ]
