# Generated by Django 3.1.2 on 2021-02-27 05:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='zone',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='climate.hardinesszone'),
        ),
        migrations.AlterField(
            model_name='hardinesszone',
            name='highRange',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-65), django.core.validators.MaxValueValidator(65)]),
        ),
        migrations.AlterField(
            model_name='hardinesszone',
            name='lowRange',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(-65), django.core.validators.MaxValueValidator(65)]),
        ),
    ]
