# Generated by Django 3.1.2 on 2021-02-28 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_auto_20210226_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='firstFrost',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lastFrost',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
