# Generated by Django 3.2.2 on 2021-05-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("climate", "0003_auto_20210227_1900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climate",
            name="firstFrost",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="climate",
            name="lastFrost",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="climate",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                default=13,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="climate.hardinesszone",
            ),
        ),
    ]
