# Generated by Django 2.2.7 on 2019-11-24 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=309)),
                ('species', models.CharField(max_length=30)),
                ('genus', models.CharField(max_length=30)),
                ('height', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'All crops must have a height greater than zero centimeters')])),
                ('weight', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'All crops must have a weight greater than zero centimeters')])),
                ('yieldKg', models.SmallIntegerField(db_column='yield', validators=[django.core.validators.MinValueValidator(1, 'All crops must have a yield of more than one kg')])),
                ('gallonsPerWeek', models.FloatField()),
                ('sunPerDay', models.CharField(choices=[('F', 'Full Sun'), ('P', 'Part Sun'), ('S', 'Shade')], max_length=1, null=True)),
                ('category', models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed'), ('L', 'Legume')], max_length=2, null=True)),
                ('daysToHarvest', models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(365)])),
            ],
            options={
                'db_table': 'crop',
            },
        ),
    ]
