# Generated by Django 3.0.3 on 2020-04-05 02:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('company', models.CharField(max_length=30, null=True)),
                ('organic', models.BooleanField(null=True)),
                ('treated', models.BooleanField(null=True)),
                ('hybrid', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'genus',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aria.Crop')),
                ('garden', models.ForeignKey(db_column='garden', on_delete=django.db.models.deletion.CASCADE, to='aria.Plot')),
            ],
            options={
                'db_table': 'plot',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=30)),
                ('common_name', models.CharField(max_length=30, null=True)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Genus')),
            ],
            options={
                'db_table': 'species',
                'unique_together': {('species', 'genus')},
            },
        ),
        migrations.CreateModel(
            name='PlotCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Plot')),
            ],
            options={
                'db_table': 'plotCoordinate',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germination', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('depth', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('pattern', models.CharField(choices=[('R', 'row'), ('M', 'mound'), ('P', 'pot'), ('T', 'trellis'), ('S', 'scatter')], max_length=1, null=True)),
                ('spacing', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ('frost', models.CharField(choices=[('F', 'first frost'), ('L', 'last frost')], max_length=1, null=True)),
                ('date', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(choices=[('I', 'start inside'), ('O', 'direct sow'), ('T', 'transplant')], max_length=1, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Crop')),
                ('transplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Plant')),
            ],
            options={
                'db_table': 'plant',
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('variety', models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed'), ('L', 'Legume')], max_length=1, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Crop')),
            ],
            options={
                'db_table': 'harvest',
            },
        ),
        migrations.CreateModel(
            name='Grow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.CharField(choices=[('F', 'full sun'), ('P', 'part sun'), ('S', 'shade')], max_length=1, null=True)),
                ('soil', models.CharField(max_length=30, null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Crop')),
            ],
            options={
                'db_table': 'grow',
            },
        ),
        migrations.CreateModel(
            name='CropPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField()),
                ('Y', models.FloatField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Plot')),
            ],
            options={
                'db_table': 'cropPosition',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Species'),
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subspecies', models.CharField(max_length=30)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Species')),
            ],
            options={
                'db_table': 'subspecies',
                'unique_together': {('subspecies', 'species')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('id', 'species')},
        ),
    ]
