# Generated by Django 2.2.7 on 2019-11-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
