# Generated by Django 3.0.3 on 2020-04-08 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0002_auto_20200404_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='grow',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aria.Grow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvest',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
            preserve_default=False,
        ),
    ]
