# Generated by Django 3.0.3 on 2020-04-08 02:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0003_auto_20200407_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='date',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='frost',
            field=models.CharField(choices=[('F', 'first frost'), ('L', 'last frost')], max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('I', 'start inside'), ('O', 'direct sow'), ('T', 'transplant')], max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pattern',
            field=models.CharField(choices=[('R', 'row'), ('M', 'mound'), ('P', 'pot'), ('T', 'trellis'), ('S', 'scatter')], max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spacing',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='transplant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
    ]
