# Generated by Django 2.2.7 on 2019-11-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0003_crop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crop',
        ),
    ]
