# Generated by Django 2.2.7 on 2019-11-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0007_auto_20191123_2150'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
