# Generated by Django 2.2.7 on 2019-11-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0008_auto_20191123_2203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table='species ',
        ),
    ]
