# Generated by Django 3.0.6 on 2020-05-10 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0008_auto_20200407_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grow',
            name='sun',
            field=models.CharField(choices=[('F', 'Full sun'), ('P', 'Part sun'), ('S', 'Shade')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='begin',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='end',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='variety',
            field=models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed'), ('L', 'Legume')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='date',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('I', 'Start inside'), ('O', 'Direct sow'), ('T', 'Transplant')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pattern',
            field=models.CharField(choices=[('R', 'Row'), ('M', 'Mound'), ('P', 'Pot'), ('T', 'Trellis'), ('S', 'Scatter')], default=None, max_length=1),
        ),
    ]
