# Generated by Django 2.2.6 on 2020-02-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0009_auto_20191123_2208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
