# Generated by Django 3.0.6 on 2020-10-14 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0009_auto_20200516_2241'),
        ('aria', '0009_auto_20200509_2104'),
    ]

    operations = [
    ]
