# Generated by Django 2.2.6 on 2020-02-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0010_auto_20200228_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Genus')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Species')),
            ],
            options={
                'db_table': 'taxonomy',
            },
        ),
    ]
