# Generated by Django 2.2.6 on 2020-02-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0011_taxonomy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='taxonomy',
            new_name='species',
        ),
        migrations.DeleteModel(
            name='Taxonomy',
        ),
    ]
