# Generated by Django 3.0.6 on 2020-10-17 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0012_auto_20201016_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='location',
            field=models.CharField(choices=[('I', 'Start inside'), ('O', 'Direct sow')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='plant',
            name='transplant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
    ]
