# Generated by Django 2.2.6 on 2020-03-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0012_auto_20200228_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='category',
            field=models.CharField(choices=[('R', 'Root'), ('G', 'Leafy green'), ('F', 'Fruit'), ('N', 'Nut'), ('S', 'Seed'), ('L', 'Legume')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='sunPerDay',
            field=models.CharField(choices=[('F', 'Full Sun'), ('P', 'Part Sun'), ('S', 'Shade')], default=None, max_length=1, null=True),
        ),
    ]
