# Generated by Django 3.0.3 on 2020-03-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0013_auto_20200229_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genus',
            name='genus',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
