# Generated by Django 3.0.3 on 2020-03-31 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0014_auto_20200329_1749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('crop', 'species')},
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('species', 'genus')},
        ),
    ]
