# Generated by Django 3.0.3 on 2020-03-31 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0015_auto_20200330_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subspecies', models.CharField(max_length=30)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Species')),
            ],
            options={
                'db_table': 'subspecies',
                'unique_together': {('subspecies', 'species')},
            },
        ),
    ]
