# Generated by Django 3.0.3 on 2020-04-04 05:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0016_auto_20200330_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grow',
            fields=[
                ('grow', models.AutoField(primary_key=True, serialize=False)),
                ('sun', models.CharField(choices=[('F', 'full sun'), ('P', 'part sun'), ('S', 'shade')], max_length=1, null=True)),
                ('soil', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest', models.AutoField(primary_key=True, serialize=False)),
                ('begin', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germination', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('depth', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('pattern', models.CharField(choices=[('R', 'row'), ('M', 'mound'), ('P', 'pot'), ('T', 'trellis'), ('S', 'scatter')], max_length=1, null=True)),
                ('spacing', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(50)])),
                ('frost', models.CharField(choices=[('F', 'first frost'), ('L', 'last frost')], max_length=1, null=True)),
                ('date', models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location', models.CharField(choices=[('I', 'start inside'), ('O', 'direct sow'), ('T', 'transplant')], max_length=1, null=True)),
                ('transplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aria.Plant')),
            ],
        ),
        migrations.RemoveField(
            model_name='growingstyle',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='daysToHarvest',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='gallonsPerWeek',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='height',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='sunPerDay',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='yieldKg',
        ),
        migrations.AddField(
            model_name='crop',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='hybrid',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='organic',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='treated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Species'),
        ),
        migrations.DeleteModel(
            name='CropType',
        ),
        migrations.DeleteModel(
            name='GrowingStyle',
        ),
        migrations.AddField(
            model_name='crop',
            name='grow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Grow'),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Harvest'),
        ),
        migrations.AddField(
            model_name='crop',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aria.Plant'),
        ),
    ]
