# Generated by Django 3.0.3 on 2020-04-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aria', '0018_harvest_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='form',
            new_name='variety',
        ),
    ]
